/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ConActif;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import models.DetteDetaillee;

/**
 *
 * @author Luz
 */
public class ListeHisto extends javax.swing.JPanel {

    /**
     * Creates new form Panel4
     */
   private JPanel panel;
   private ConActif conactif;

    public void setPanel(JPanel panel) {
        this.panel = panel;
    }
    public ListeHisto() {
        initComponents();
        this.conactif = new ConActif();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        retourner = new javax.swing.JButton();

        jTable1 = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Libellé", "Date de création échéancier", "Montant dû", "Id"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel1.setText("Historique des redevables");

        retourner.setText("Retourner");
        retourner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retournerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(302, 302, 302))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(265, 265, 265)
                .addComponent(retourner)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(retourner)
                .addContainerGap(76, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void retournerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retournerActionPerformed
        ((CardLayout)panel.getLayout()).show(panel, "p2");// TODO add your handling code here:
    }//GEN-LAST:event_retournerActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       if(evt.getClickCount() == 2){
        JTextField nom = ((DetailAH)panel.getComponent(5)).getNom();
        JTextField libelle = ((DetailAH)panel.getComponent(5)).getLibelle();
        JTextField mail = ((DetailAH)panel.getComponent(5)).getMail();
        JTextField montant = ((DetailAH)panel.getComponent(5)).getMontant();
        JTextField info = ((DetailAH)panel.getComponent(5)).getInfocomplementaire();
        JTextField actionEntre = ((DetailAH)panel.getComponent(5)).getActionentreprendre();
        JTextField actionEffect = ((DetailAH)panel.getComponent(5)).getActioneffectuee();
        JTextField idDette = ((DetailAH)panel.getComponent(5)).getIdDette();
        JTable echeances = ((DetailAH)panel.getComponent(5)).getListeEcheances();
        idDette.setVisible(false);
         DetteDetaillee detteAffiche = conactif.showDetail(4,jTable1,echeances,idDette, nom, mail , libelle, montant, info, actionEntre, actionEffect);
        ((DetailAH)panel.getComponent(5)).setDetteEnregistre(detteAffiche);
        ((CardLayout)panel.getLayout()).show(panel, "p5"); 
       } 
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton retourner;
    // End of variables declaration//GEN-END:variables

    public JTable getjTable1() {
        return jTable1;
    }

   

}
