/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.CardLayout;

/**
 *
 * @author Luz
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        connexion.setPanel(mainPanel); //funcoon dar cards a todos los paneneles
        menu.setPanel(mainPanel); // pasamso todo el conjuntp de cartas a los paneles para que sepan que carta poner
        rechercheHisto.setPanel(mainPanel); 
        listeHisto.setPanel(mainPanel);
        actif.setPanel(mainPanel);
        detailActif.setPanel(mainPanel);
        editionAH.setPanel(mainPanel);
        creation.setPanel(mainPanel);
        mailRedevable.setPanel(mainPanel);
        mailAgent.setPanel(mainPanel);
        agent.setPanel(mainPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        connexion = new views.Connexion();
        menu = new views.Menu();
        rechercheHisto = new views.RechercheHisto();
        listeHisto = new views.ListeHisto();
        actif = new views.Actif();
        detailActif = new views.DetailAH();
        editionAH = new views.EditionAH();
        creation = new views.Creation();
        agent = new views.Agent();
        mailRedevable = new views.MailRedevable();
        mailAgent = new views.MailAgent();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(connexion, "p0");
        mainPanel.add(menu, "p1");
        mainPanel.add(rechercheHisto, "p2");
        mainPanel.add(listeHisto, "p3");
        mainPanel.add(actif, "p4");
        mainPanel.add(detailActif, "p5");
        mainPanel.add(editionAH, "p6");
        mainPanel.add(creation, "p7");
        mainPanel.add(agent, "p8");
        mainPanel.add(mailRedevable, "p9");
        mainPanel.add(mailAgent, "p10");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private views.Actif actif;
    private views.Agent agent;
    private views.Connexion connexion;
    private views.Creation creation;
    private views.DetailAH detailActif;
    private views.EditionAH editionAH;
    private views.ListeHisto listeHisto;
    private views.MailAgent mailAgent;
    private views.MailRedevable mailRedevable;
    private javax.swing.JPanel mainPanel;
    private views.Menu menu;
    private views.RechercheHisto rechercheHisto;
    // End of variables declaration//GEN-END:variables
}
