/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ConCreation;
import controllers.ConExcel;
import java.awt.CardLayout;
import java.io.File;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Luz
 */
public class OptionsCreation extends javax.swing.JPanel {

    /**
     * Creates new form OptionsCreation
     */
    private JPanel panel;
    private ConExcel conExcel;
    private ConCreation conCreation;
    
      public void setPanel(JPanel panel) {
        this.panel = panel;
    }
    
    public OptionsCreation() {
        initComponents();
        conExcel = new ConExcel();
        conCreation = new ConCreation();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        manuel = new javax.swing.JButton();
        excel = new javax.swing.JButton();
        annuler = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jLabel1.setText("Creation d'une redevable");

        jLabel2.setText("Choisissez la manière dont vous allez créer le redevable ");

        manuel.setText("Saisi Manuel");
        manuel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manuelActionPerformed(evt);
            }
        });

        excel.setText("Import d'Excel");
        excel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excelActionPerformed(evt);
            }
        });

        annuler.setText("Annuler");
        annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(manuel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(excel)
                                .addGap(12, 12, 12))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(annuler)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manuel)
                    .addComponent(excel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(annuler)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void annulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerActionPerformed
       ((CardLayout)panel.getLayout()).show(panel, "p1");
    }//GEN-LAST:event_annulerActionPerformed

    private void manuelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manuelActionPerformed
      JComboBox agentComptable = ((Creation)panel.getComponent(7)).getListeAgent();
      ((Creation)panel.getComponent(7)).setListeAgent(conCreation.afficherAgent(agentComptable));
      JComboBox nbEcheances =((Creation)panel.getComponent(7)).getNbEcheances();
      ((Creation)panel.getComponent(7)).setNbEcheances(conCreation.afficherEcheances(nbEcheances));
      ((CardLayout)panel.getLayout()).show(panel, "p7");
    }//GEN-LAST:event_manuelActionPerformed

    private void excelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excelActionPerformed
        File fichier = conExcel.chosirFichier(panel);
        JTextField libelle = ((Creation)panel.getComponent(7)).getLibelle();
        JTextField nom = ((Creation)panel.getComponent(7)).getNomRedevable();
        JTextField montant = ((Creation)panel.getComponent(7)).getMontant();
        JTable echeances = ((Creation)panel.getComponent(7)).getListeEcheances();
        JComboBox agentComptable = ((Creation)panel.getComponent(7)).getListeAgent();
        ((Creation)panel.getComponent(7)).setListeAgent(conCreation.afficherAgent(agentComptable));
        conExcel.ajouterDonnees(fichier, nom, libelle, montant, echeances);
        ((CardLayout)panel.getLayout()).show(panel, "p7");
    }//GEN-LAST:event_excelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annuler;
    private javax.swing.JButton excel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton manuel;
    // End of variables declaration//GEN-END:variables
}
